//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWeb.Framework.Data.DB.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDWebShopSQL : DbContext
    {
        public BDWebShopSQL()
            : base("name=BDWebShopSQL")
        {
            Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TCabeceraVenta> TCabeceraVenta { get; set; }
        public virtual DbSet<TCategoria> TCategoria { get; set; }
        public virtual DbSet<TCliente> TCliente { get; set; }
        public virtual DbSet<TDetalleVenta> TDetalleVenta { get; set; }
        public virtual DbSet<TOrdenVenta> TOrdenVenta { get; set; }
        public virtual DbSet<TProducto> TProducto { get; set; }
        public virtual DbSet<TSubCategoria> TSubCategoria { get; set; }
    }
}
