//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWeb.Framework.Data.DB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCategoria
    {
        public TCategoria()
        {
            this.TSubCategoria = new HashSet<TSubCategoria>();
        }
    
        public int CodCategoria { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<TSubCategoria> TSubCategoria { get; set; }
    }
}
