//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWeb.Framework.Data.DB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCliente
    {
        public TCliente()
        {
            this.TCabeceraVenta = new HashSet<TCabeceraVenta>();
            this.TOrdenVenta = new HashSet<TOrdenVenta>();
        }
    
        public int CodCliente { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Genero { get; set; }
        public string TipoDocumento { get; set; }
        public string NroDocumento { get; set; }
        public string Email { get; set; }
        public string Provincia { get; set; }
        public string Ciudad { get; set; }
        public string Distrito { get; set; }
        public string Direccion { get; set; }
        public string Usuario { get; set; }
        public string Contrasena { get; set; }
        public string RazonSocial { get; set; }
        public string Telefono { get; set; }
    
        public virtual ICollection<TCabeceraVenta> TCabeceraVenta { get; set; }
        public virtual ICollection<TOrdenVenta> TOrdenVenta { get; set; }
    }
}
