//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWeb.Tests.ShopWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TCliente", Namespace="http://schemas.datacontract.org/2004/07/AppWeb.Framework.Data.DB.Model")]
    [System.SerializableAttribute()]
    public partial class TCliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContrasenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GeneroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NroDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazonSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppWeb.Tests.ShopWS.TCabeceraVenta[] TCabeceraVentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppWeb.Tests.ShopWS.TOrdenVenta[] TOrdenVentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ciudad {
            get {
                return this.CiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadField, value) != true)) {
                    this.CiudadField = value;
                    this.RaisePropertyChanged("Ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodCliente {
            get {
                return this.CodClienteField;
            }
            set {
                if ((this.CodClienteField.Equals(value) != true)) {
                    this.CodClienteField = value;
                    this.RaisePropertyChanged("CodCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasena {
            get {
                return this.ContrasenaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContrasenaField, value) != true)) {
                    this.ContrasenaField = value;
                    this.RaisePropertyChanged("Contrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distrito {
            get {
                return this.DistritoField;
            }
            set {
                if ((object.ReferenceEquals(this.DistritoField, value) != true)) {
                    this.DistritoField = value;
                    this.RaisePropertyChanged("Distrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Genero {
            get {
                return this.GeneroField;
            }
            set {
                if ((object.ReferenceEquals(this.GeneroField, value) != true)) {
                    this.GeneroField = value;
                    this.RaisePropertyChanged("Genero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroDocumento {
            get {
                return this.NroDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.NroDocumentoField, value) != true)) {
                    this.NroDocumentoField = value;
                    this.RaisePropertyChanged("NroDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia {
            get {
                return this.ProvinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinciaField, value) != true)) {
                    this.ProvinciaField = value;
                    this.RaisePropertyChanged("Provincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial {
            get {
                return this.RazonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.RazonSocialField, value) != true)) {
                    this.RazonSocialField = value;
                    this.RaisePropertyChanged("RazonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppWeb.Tests.ShopWS.TCabeceraVenta[] TCabeceraVenta {
            get {
                return this.TCabeceraVentaField;
            }
            set {
                if ((object.ReferenceEquals(this.TCabeceraVentaField, value) != true)) {
                    this.TCabeceraVentaField = value;
                    this.RaisePropertyChanged("TCabeceraVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppWeb.Tests.ShopWS.TOrdenVenta[] TOrdenVenta {
            get {
                return this.TOrdenVentaField;
            }
            set {
                if ((object.ReferenceEquals(this.TOrdenVentaField, value) != true)) {
                    this.TOrdenVentaField = value;
                    this.RaisePropertyChanged("TOrdenVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoField, value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TCabeceraVenta", Namespace="http://schemas.datacontract.org/2004/07/AppWeb.Framework.Data.DB.Model")]
    [System.SerializableAttribute()]
    public partial class TCabeceraVenta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaVentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NroDetalleVentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppWeb.Tests.ShopWS.TCliente TClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppWeb.Tests.ShopWS.TDetalleVenta TDetalleVentaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodCliente {
            get {
                return this.CodClienteField;
            }
            set {
                if ((this.CodClienteField.Equals(value) != true)) {
                    this.CodClienteField = value;
                    this.RaisePropertyChanged("CodCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaVenta {
            get {
                return this.FechaVentaField;
            }
            set {
                if ((this.FechaVentaField.Equals(value) != true)) {
                    this.FechaVentaField = value;
                    this.RaisePropertyChanged("FechaVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NroDetalleVenta {
            get {
                return this.NroDetalleVentaField;
            }
            set {
                if ((this.NroDetalleVentaField.Equals(value) != true)) {
                    this.NroDetalleVentaField = value;
                    this.RaisePropertyChanged("NroDetalleVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppWeb.Tests.ShopWS.TCliente TCliente {
            get {
                return this.TClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.TClienteField, value) != true)) {
                    this.TClienteField = value;
                    this.RaisePropertyChanged("TCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppWeb.Tests.ShopWS.TDetalleVenta TDetalleVenta {
            get {
                return this.TDetalleVentaField;
            }
            set {
                if ((object.ReferenceEquals(this.TDetalleVentaField, value) != true)) {
                    this.TDetalleVentaField = value;
                    this.RaisePropertyChanged("TDetalleVenta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TOrdenVenta", Namespace="http://schemas.datacontract.org/2004/07/AppWeb.Framework.Data.DB.Model")]
    [System.SerializableAttribute()]
    public partial class TOrdenVenta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CodClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaEntregaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaVentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NroVentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppWeb.Tests.ShopWS.TCliente TClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppWeb.Tests.ShopWS.TDetalleVenta[] TDetalleVentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CodCliente {
            get {
                return this.CodClienteField;
            }
            set {
                if ((this.CodClienteField.Equals(value) != true)) {
                    this.CodClienteField = value;
                    this.RaisePropertyChanged("CodCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaEntrega {
            get {
                return this.FechaEntregaField;
            }
            set {
                if ((this.FechaEntregaField.Equals(value) != true)) {
                    this.FechaEntregaField = value;
                    this.RaisePropertyChanged("FechaEntrega");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaVenta {
            get {
                return this.FechaVentaField;
            }
            set {
                if ((this.FechaVentaField.Equals(value) != true)) {
                    this.FechaVentaField = value;
                    this.RaisePropertyChanged("FechaVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NroVenta {
            get {
                return this.NroVentaField;
            }
            set {
                if ((this.NroVentaField.Equals(value) != true)) {
                    this.NroVentaField = value;
                    this.RaisePropertyChanged("NroVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppWeb.Tests.ShopWS.TCliente TCliente {
            get {
                return this.TClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.TClienteField, value) != true)) {
                    this.TClienteField = value;
                    this.RaisePropertyChanged("TCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppWeb.Tests.ShopWS.TDetalleVenta[] TDetalleVenta {
            get {
                return this.TDetalleVentaField;
            }
            set {
                if ((object.ReferenceEquals(this.TDetalleVentaField, value) != true)) {
                    this.TDetalleVentaField = value;
                    this.RaisePropertyChanged("TDetalleVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TDetalleVenta", Namespace="http://schemas.datacontract.org/2004/07/AppWeb.Framework.Data.DB.Model")]
    [System.SerializableAttribute()]
    public partial class TDetalleVenta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CodProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NroDetalleVentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NroVentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PrecioUnitarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppWeb.Tests.ShopWS.TCabeceraVenta[] TCabeceraVentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppWeb.Tests.ShopWS.TOrdenVenta TOrdenVentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppWeb.Tests.ShopWS.TProducto TProductoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CodProducto {
            get {
                return this.CodProductoField;
            }
            set {
                if ((this.CodProductoField.Equals(value) != true)) {
                    this.CodProductoField = value;
                    this.RaisePropertyChanged("CodProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NroDetalleVenta {
            get {
                return this.NroDetalleVentaField;
            }
            set {
                if ((this.NroDetalleVentaField.Equals(value) != true)) {
                    this.NroDetalleVentaField = value;
                    this.RaisePropertyChanged("NroDetalleVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NroVenta {
            get {
                return this.NroVentaField;
            }
            set {
                if ((this.NroVentaField.Equals(value) != true)) {
                    this.NroVentaField = value;
                    this.RaisePropertyChanged("NroVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PrecioUnitario {
            get {
                return this.PrecioUnitarioField;
            }
            set {
                if ((this.PrecioUnitarioField.Equals(value) != true)) {
                    this.PrecioUnitarioField = value;
                    this.RaisePropertyChanged("PrecioUnitario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppWeb.Tests.ShopWS.TCabeceraVenta[] TCabeceraVenta {
            get {
                return this.TCabeceraVentaField;
            }
            set {
                if ((object.ReferenceEquals(this.TCabeceraVentaField, value) != true)) {
                    this.TCabeceraVentaField = value;
                    this.RaisePropertyChanged("TCabeceraVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppWeb.Tests.ShopWS.TOrdenVenta TOrdenVenta {
            get {
                return this.TOrdenVentaField;
            }
            set {
                if ((object.ReferenceEquals(this.TOrdenVentaField, value) != true)) {
                    this.TOrdenVentaField = value;
                    this.RaisePropertyChanged("TOrdenVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppWeb.Tests.ShopWS.TProducto TProducto {
            get {
                return this.TProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.TProductoField, value) != true)) {
                    this.TProductoField = value;
                    this.RaisePropertyChanged("TProducto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TProducto", Namespace="http://schemas.datacontract.org/2004/07/AppWeb.Framework.Data.DB.Model")]
    [System.SerializableAttribute()]
    public partial class TProducto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodSubCategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EspecificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PrecioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppWeb.Tests.ShopWS.TDetalleVenta[] TDetalleVentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppWeb.Tests.ShopWS.TSubCategoria TSubCategoriaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodProducto {
            get {
                return this.CodProductoField;
            }
            set {
                if ((this.CodProductoField.Equals(value) != true)) {
                    this.CodProductoField = value;
                    this.RaisePropertyChanged("CodProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodSubCategoria {
            get {
                return this.CodSubCategoriaField;
            }
            set {
                if ((this.CodSubCategoriaField.Equals(value) != true)) {
                    this.CodSubCategoriaField = value;
                    this.RaisePropertyChanged("CodSubCategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Especificacion {
            get {
                return this.EspecificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.EspecificacionField, value) != true)) {
                    this.EspecificacionField = value;
                    this.RaisePropertyChanged("Especificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Stock {
            get {
                return this.StockField;
            }
            set {
                if ((this.StockField.Equals(value) != true)) {
                    this.StockField = value;
                    this.RaisePropertyChanged("Stock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppWeb.Tests.ShopWS.TDetalleVenta[] TDetalleVenta {
            get {
                return this.TDetalleVentaField;
            }
            set {
                if ((object.ReferenceEquals(this.TDetalleVentaField, value) != true)) {
                    this.TDetalleVentaField = value;
                    this.RaisePropertyChanged("TDetalleVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppWeb.Tests.ShopWS.TSubCategoria TSubCategoria {
            get {
                return this.TSubCategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.TSubCategoriaField, value) != true)) {
                    this.TSubCategoriaField = value;
                    this.RaisePropertyChanged("TSubCategoria");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TSubCategoria", Namespace="http://schemas.datacontract.org/2004/07/AppWeb.Framework.Data.DB.Model")]
    [System.SerializableAttribute()]
    public partial class TSubCategoria : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodCategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodSubCategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppWeb.Tests.ShopWS.TCategoria TCategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppWeb.Tests.ShopWS.TProducto[] TProductoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodCategoria {
            get {
                return this.CodCategoriaField;
            }
            set {
                if ((this.CodCategoriaField.Equals(value) != true)) {
                    this.CodCategoriaField = value;
                    this.RaisePropertyChanged("CodCategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodSubCategoria {
            get {
                return this.CodSubCategoriaField;
            }
            set {
                if ((this.CodSubCategoriaField.Equals(value) != true)) {
                    this.CodSubCategoriaField = value;
                    this.RaisePropertyChanged("CodSubCategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppWeb.Tests.ShopWS.TCategoria TCategoria {
            get {
                return this.TCategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.TCategoriaField, value) != true)) {
                    this.TCategoriaField = value;
                    this.RaisePropertyChanged("TCategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppWeb.Tests.ShopWS.TProducto[] TProducto {
            get {
                return this.TProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.TProductoField, value) != true)) {
                    this.TProductoField = value;
                    this.RaisePropertyChanged("TProducto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TCategoria", Namespace="http://schemas.datacontract.org/2004/07/AppWeb.Framework.Data.DB.Model")]
    [System.SerializableAttribute()]
    public partial class TCategoria : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodCategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppWeb.Tests.ShopWS.TSubCategoria[] TSubCategoriaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodCategoria {
            get {
                return this.CodCategoriaField;
            }
            set {
                if ((this.CodCategoriaField.Equals(value) != true)) {
                    this.CodCategoriaField = value;
                    this.RaisePropertyChanged("CodCategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppWeb.Tests.ShopWS.TSubCategoria[] TSubCategoria {
            get {
                return this.TSubCategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.TSubCategoriaField, value) != true)) {
                    this.TSubCategoriaField = value;
                    this.RaisePropertyChanged("TSubCategoria");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ShopWS.IServiceShopSoa")]
    public interface IServiceShopSoa {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceShopSoa/AgregarCliente", ReplyAction="http://tempuri.org/IServiceShopSoa/AgregarClienteResponse")]
        AppWeb.Tests.ShopWS.TCliente AgregarCliente(AppWeb.Tests.ShopWS.TCliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceShopSoa/AgregarCliente", ReplyAction="http://tempuri.org/IServiceShopSoa/AgregarClienteResponse")]
        System.Threading.Tasks.Task<AppWeb.Tests.ShopWS.TCliente> AgregarClienteAsync(AppWeb.Tests.ShopWS.TCliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceShopSoa/ActualizarCliente", ReplyAction="http://tempuri.org/IServiceShopSoa/ActualizarClienteResponse")]
        AppWeb.Tests.ShopWS.TCliente ActualizarCliente(AppWeb.Tests.ShopWS.TCliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceShopSoa/ActualizarCliente", ReplyAction="http://tempuri.org/IServiceShopSoa/ActualizarClienteResponse")]
        System.Threading.Tasks.Task<AppWeb.Tests.ShopWS.TCliente> ActualizarClienteAsync(AppWeb.Tests.ShopWS.TCliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceShopSoa/AgregarProducto", ReplyAction="http://tempuri.org/IServiceShopSoa/AgregarProductoResponse")]
        AppWeb.Tests.ShopWS.TProducto AgregarProducto(AppWeb.Tests.ShopWS.TProducto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceShopSoa/AgregarProducto", ReplyAction="http://tempuri.org/IServiceShopSoa/AgregarProductoResponse")]
        System.Threading.Tasks.Task<AppWeb.Tests.ShopWS.TProducto> AgregarProductoAsync(AppWeb.Tests.ShopWS.TProducto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceShopSoa/ActualizarProducto", ReplyAction="http://tempuri.org/IServiceShopSoa/ActualizarProductoResponse")]
        AppWeb.Tests.ShopWS.TProducto ActualizarProducto(AppWeb.Tests.ShopWS.TProducto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceShopSoa/ActualizarProducto", ReplyAction="http://tempuri.org/IServiceShopSoa/ActualizarProductoResponse")]
        System.Threading.Tasks.Task<AppWeb.Tests.ShopWS.TProducto> ActualizarProductoAsync(AppWeb.Tests.ShopWS.TProducto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceShopSoa/BorrarProducto", ReplyAction="http://tempuri.org/IServiceShopSoa/BorrarProductoResponse")]
        bool BorrarProducto(AppWeb.Tests.ShopWS.TProducto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceShopSoa/BorrarProducto", ReplyAction="http://tempuri.org/IServiceShopSoa/BorrarProductoResponse")]
        System.Threading.Tasks.Task<bool> BorrarProductoAsync(AppWeb.Tests.ShopWS.TProducto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceShopSoa/AgregarSubCategoria", ReplyAction="http://tempuri.org/IServiceShopSoa/AgregarSubCategoriaResponse")]
        AppWeb.Tests.ShopWS.TSubCategoria AgregarSubCategoria(AppWeb.Tests.ShopWS.TSubCategoria subCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceShopSoa/AgregarSubCategoria", ReplyAction="http://tempuri.org/IServiceShopSoa/AgregarSubCategoriaResponse")]
        System.Threading.Tasks.Task<AppWeb.Tests.ShopWS.TSubCategoria> AgregarSubCategoriaAsync(AppWeb.Tests.ShopWS.TSubCategoria subCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceShopSoa/ActualizarSubCategoria", ReplyAction="http://tempuri.org/IServiceShopSoa/ActualizarSubCategoriaResponse")]
        AppWeb.Tests.ShopWS.TSubCategoria ActualizarSubCategoria(AppWeb.Tests.ShopWS.TSubCategoria subCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceShopSoa/ActualizarSubCategoria", ReplyAction="http://tempuri.org/IServiceShopSoa/ActualizarSubCategoriaResponse")]
        System.Threading.Tasks.Task<AppWeb.Tests.ShopWS.TSubCategoria> ActualizarSubCategoriaAsync(AppWeb.Tests.ShopWS.TSubCategoria subCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceShopSoa/BorrarSubCategoria", ReplyAction="http://tempuri.org/IServiceShopSoa/BorrarSubCategoriaResponse")]
        bool BorrarSubCategoria(AppWeb.Tests.ShopWS.TSubCategoria subCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceShopSoa/BorrarSubCategoria", ReplyAction="http://tempuri.org/IServiceShopSoa/BorrarSubCategoriaResponse")]
        System.Threading.Tasks.Task<bool> BorrarSubCategoriaAsync(AppWeb.Tests.ShopWS.TSubCategoria subCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceShopSoa/AgregarCategoria", ReplyAction="http://tempuri.org/IServiceShopSoa/AgregarCategoriaResponse")]
        AppWeb.Tests.ShopWS.TCategoria AgregarCategoria(AppWeb.Tests.ShopWS.TCategoria categoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceShopSoa/AgregarCategoria", ReplyAction="http://tempuri.org/IServiceShopSoa/AgregarCategoriaResponse")]
        System.Threading.Tasks.Task<AppWeb.Tests.ShopWS.TCategoria> AgregarCategoriaAsync(AppWeb.Tests.ShopWS.TCategoria categoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceShopSoa/ActualizarCategoria", ReplyAction="http://tempuri.org/IServiceShopSoa/ActualizarCategoriaResponse")]
        AppWeb.Tests.ShopWS.TCategoria ActualizarCategoria(AppWeb.Tests.ShopWS.TCategoria categoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceShopSoa/ActualizarCategoria", ReplyAction="http://tempuri.org/IServiceShopSoa/ActualizarCategoriaResponse")]
        System.Threading.Tasks.Task<AppWeb.Tests.ShopWS.TCategoria> ActualizarCategoriaAsync(AppWeb.Tests.ShopWS.TCategoria categoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceShopSoa/BorrarCategoria", ReplyAction="http://tempuri.org/IServiceShopSoa/BorrarCategoriaResponse")]
        bool BorrarCategoria(AppWeb.Tests.ShopWS.TCategoria categoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceShopSoa/BorrarCategoria", ReplyAction="http://tempuri.org/IServiceShopSoa/BorrarCategoriaResponse")]
        System.Threading.Tasks.Task<bool> BorrarCategoriaAsync(AppWeb.Tests.ShopWS.TCategoria categoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceShopSoa/AgregarNuevaVenta", ReplyAction="http://tempuri.org/IServiceShopSoa/AgregarNuevaVentaResponse")]
        AppWeb.Tests.ShopWS.TOrdenVenta AgregarNuevaVenta(AppWeb.Tests.ShopWS.TCliente cliente, AppWeb.Tests.ShopWS.TProducto[] productos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceShopSoa/AgregarNuevaVenta", ReplyAction="http://tempuri.org/IServiceShopSoa/AgregarNuevaVentaResponse")]
        System.Threading.Tasks.Task<AppWeb.Tests.ShopWS.TOrdenVenta> AgregarNuevaVentaAsync(AppWeb.Tests.ShopWS.TCliente cliente, AppWeb.Tests.ShopWS.TProducto[] productos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceShopSoa/ValidarLoginCliente", ReplyAction="http://tempuri.org/IServiceShopSoa/ValidarLoginClienteResponse")]
        bool ValidarLoginCliente(string usuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceShopSoa/ValidarLoginCliente", ReplyAction="http://tempuri.org/IServiceShopSoa/ValidarLoginClienteResponse")]
        System.Threading.Tasks.Task<bool> ValidarLoginClienteAsync(string usuario, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceShopSoaChannel : AppWeb.Tests.ShopWS.IServiceShopSoa, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceShopSoaClient : System.ServiceModel.ClientBase<AppWeb.Tests.ShopWS.IServiceShopSoa>, AppWeb.Tests.ShopWS.IServiceShopSoa {
        
        public ServiceShopSoaClient() {
        }
        
        public ServiceShopSoaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceShopSoaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceShopSoaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceShopSoaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AppWeb.Tests.ShopWS.TCliente AgregarCliente(AppWeb.Tests.ShopWS.TCliente cliente) {
            return base.Channel.AgregarCliente(cliente);
        }
        
        public System.Threading.Tasks.Task<AppWeb.Tests.ShopWS.TCliente> AgregarClienteAsync(AppWeb.Tests.ShopWS.TCliente cliente) {
            return base.Channel.AgregarClienteAsync(cliente);
        }
        
        public AppWeb.Tests.ShopWS.TCliente ActualizarCliente(AppWeb.Tests.ShopWS.TCliente cliente) {
            return base.Channel.ActualizarCliente(cliente);
        }
        
        public System.Threading.Tasks.Task<AppWeb.Tests.ShopWS.TCliente> ActualizarClienteAsync(AppWeb.Tests.ShopWS.TCliente cliente) {
            return base.Channel.ActualizarClienteAsync(cliente);
        }
        
        public AppWeb.Tests.ShopWS.TProducto AgregarProducto(AppWeb.Tests.ShopWS.TProducto producto) {
            return base.Channel.AgregarProducto(producto);
        }
        
        public System.Threading.Tasks.Task<AppWeb.Tests.ShopWS.TProducto> AgregarProductoAsync(AppWeb.Tests.ShopWS.TProducto producto) {
            return base.Channel.AgregarProductoAsync(producto);
        }
        
        public AppWeb.Tests.ShopWS.TProducto ActualizarProducto(AppWeb.Tests.ShopWS.TProducto producto) {
            return base.Channel.ActualizarProducto(producto);
        }
        
        public System.Threading.Tasks.Task<AppWeb.Tests.ShopWS.TProducto> ActualizarProductoAsync(AppWeb.Tests.ShopWS.TProducto producto) {
            return base.Channel.ActualizarProductoAsync(producto);
        }
        
        public bool BorrarProducto(AppWeb.Tests.ShopWS.TProducto producto) {
            return base.Channel.BorrarProducto(producto);
        }
        
        public System.Threading.Tasks.Task<bool> BorrarProductoAsync(AppWeb.Tests.ShopWS.TProducto producto) {
            return base.Channel.BorrarProductoAsync(producto);
        }
        
        public AppWeb.Tests.ShopWS.TSubCategoria AgregarSubCategoria(AppWeb.Tests.ShopWS.TSubCategoria subCategoria) {
            return base.Channel.AgregarSubCategoria(subCategoria);
        }
        
        public System.Threading.Tasks.Task<AppWeb.Tests.ShopWS.TSubCategoria> AgregarSubCategoriaAsync(AppWeb.Tests.ShopWS.TSubCategoria subCategoria) {
            return base.Channel.AgregarSubCategoriaAsync(subCategoria);
        }
        
        public AppWeb.Tests.ShopWS.TSubCategoria ActualizarSubCategoria(AppWeb.Tests.ShopWS.TSubCategoria subCategoria) {
            return base.Channel.ActualizarSubCategoria(subCategoria);
        }
        
        public System.Threading.Tasks.Task<AppWeb.Tests.ShopWS.TSubCategoria> ActualizarSubCategoriaAsync(AppWeb.Tests.ShopWS.TSubCategoria subCategoria) {
            return base.Channel.ActualizarSubCategoriaAsync(subCategoria);
        }
        
        public bool BorrarSubCategoria(AppWeb.Tests.ShopWS.TSubCategoria subCategoria) {
            return base.Channel.BorrarSubCategoria(subCategoria);
        }
        
        public System.Threading.Tasks.Task<bool> BorrarSubCategoriaAsync(AppWeb.Tests.ShopWS.TSubCategoria subCategoria) {
            return base.Channel.BorrarSubCategoriaAsync(subCategoria);
        }
        
        public AppWeb.Tests.ShopWS.TCategoria AgregarCategoria(AppWeb.Tests.ShopWS.TCategoria categoria) {
            return base.Channel.AgregarCategoria(categoria);
        }
        
        public System.Threading.Tasks.Task<AppWeb.Tests.ShopWS.TCategoria> AgregarCategoriaAsync(AppWeb.Tests.ShopWS.TCategoria categoria) {
            return base.Channel.AgregarCategoriaAsync(categoria);
        }
        
        public AppWeb.Tests.ShopWS.TCategoria ActualizarCategoria(AppWeb.Tests.ShopWS.TCategoria categoria) {
            return base.Channel.ActualizarCategoria(categoria);
        }
        
        public System.Threading.Tasks.Task<AppWeb.Tests.ShopWS.TCategoria> ActualizarCategoriaAsync(AppWeb.Tests.ShopWS.TCategoria categoria) {
            return base.Channel.ActualizarCategoriaAsync(categoria);
        }
        
        public bool BorrarCategoria(AppWeb.Tests.ShopWS.TCategoria categoria) {
            return base.Channel.BorrarCategoria(categoria);
        }
        
        public System.Threading.Tasks.Task<bool> BorrarCategoriaAsync(AppWeb.Tests.ShopWS.TCategoria categoria) {
            return base.Channel.BorrarCategoriaAsync(categoria);
        }
        
        public AppWeb.Tests.ShopWS.TOrdenVenta AgregarNuevaVenta(AppWeb.Tests.ShopWS.TCliente cliente, AppWeb.Tests.ShopWS.TProducto[] productos) {
            return base.Channel.AgregarNuevaVenta(cliente, productos);
        }
        
        public System.Threading.Tasks.Task<AppWeb.Tests.ShopWS.TOrdenVenta> AgregarNuevaVentaAsync(AppWeb.Tests.ShopWS.TCliente cliente, AppWeb.Tests.ShopWS.TProducto[] productos) {
            return base.Channel.AgregarNuevaVentaAsync(cliente, productos);
        }
        
        public bool ValidarLoginCliente(string usuario, string password) {
            return base.Channel.ValidarLoginCliente(usuario, password);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarLoginClienteAsync(string usuario, string password) {
            return base.Channel.ValidarLoginClienteAsync(usuario, password);
        }
    }
}
