//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWeb.Framework.DB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDetalleVenta
    {
        public TDetalleVenta()
        {
            this.TCabeceraVenta = new HashSet<TCabeceraVenta>();
        }
    
        public int NroDetalleVenta { get; set; }
        public Nullable<int> NroVenta { get; set; }
        public string CodProducto { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> PrecioUnitario { get; set; }
    
        public virtual ICollection<TCabeceraVenta> TCabeceraVenta { get; set; }
        public virtual TProducto TProducto { get; set; }
        public virtual TOrdenVenta TOrdenVenta { get; set; }
    }
}
