//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWeb.Framework.DB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOrdenVenta
    {
        public TOrdenVenta()
        {
            this.TDetalleVenta = new HashSet<TDetalleVenta>();
        }
    
        public int NroVenta { get; set; }
        public Nullable<int> CodCliente { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.DateTime> FechaVenta { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
    
        public virtual TCliente TCliente { get; set; }
        public virtual ICollection<TDetalleVenta> TDetalleVenta { get; set; }
    }
}
