//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWeb.Framework.DB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TProducto
    {
        public TProducto()
        {
            this.TDetalleVenta = new HashSet<TDetalleVenta>();
        }
    
        public int CodProducto { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Especificacion { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public int CodSubCategoria { get; set; }
    
        public virtual ICollection<TDetalleVenta> TDetalleVenta { get; set; }
        public virtual TSubCategoria TSubCategoria { get; set; }
    }
}
